if settings.startup["pyalienlife-productivitymodule-on"].value == true then
data.raw["module"]["vrauks-mk02"].effect = { speed = {bonus = 0.5}, productivity = {bonus = 0.2}}
data.raw["module"]["vrauks-mk03"].effect = { speed = {bonus = 0.75}, productivity = {bonus = 0.3}}
data.raw["module"]["vrauks-mk04"].effect = { speed = {bonus = 1.0}, productivity = {bonus = 0.4}}
data.raw["module"]["scrondrix-mk02"].effect = { speed = {bonus = 3.3}, productivity = {bonus = 0.2}}
data.raw["module"]["scrondrix-mk03"].effect = { speed = {bonus = 4.96}, productivity = {bonus = 0.3}}
data.raw["module"]["scrondrix-mk04"].effect = { speed = {bonus = 6.6}, productivity = {bonus = 0.4}}
data.raw["module"]["dingrits-mk02"].effect = { speed = {bonus = 0.8}, productivity = {bonus = 0.2}}
data.raw["module"]["dingrits-mk03"].effect = { speed = {bonus = 1.6}, productivity = {bonus = 0.3}}
data.raw["module"]["dingrits-mk04"].effect = { speed = {bonus = 3.2}, productivity = {bonus = 0.4}}
data.raw["module"]["yaedols-mk02"].effect = { speed = {bonus = 12.5}, productivity = {bonus = 0.2}}
data.raw["module"]["yaedols-mk03"].effect = { speed = {bonus = 15.0}, productivity = {bonus = 0.3}}
data.raw["module"]["yaedols-mk04"].effect = { speed = {bonus = 17.5}, productivity = {bonus = 0.4}}
data.raw["module"]["phagnot-mk02"].effect = { speed = {bonus = 2.0}, productivity = {bonus = 0.2}}
data.raw["module"]["phagnot-mk03"].effect = { speed = {bonus = 3.0}, productivity = {bonus = 0.3}}
data.raw["module"]["phagnot-mk04"].effect = { speed = {bonus = 4.0}, productivity = {bonus = 0.4}}
data.raw["module"]["rennea-mk02"].effect = { speed = {bonus = 0.32}, productivity = {bonus = 0.2}}
data.raw["module"]["rennea-mk03"].effect = { speed = {bonus = 0.64}, productivity = {bonus = 0.3}}
data.raw["module"]["rennea-mk04"].effect = { speed = {bonus = 1.25}, productivity = {bonus = 0.4}}
data.raw["module"]["kmauts-mk02"].effect = { speed = {bonus = 0.4}, productivity = {bonus = 0.2}}
data.raw["module"]["kmauts-mk03"].effect = { speed = {bonus = 0.6}, productivity = {bonus = 0.3}}
data.raw["module"]["kmauts-mk04"].effect = { speed = {bonus = 0.8}, productivity = {bonus = 0.4}}
data.raw["module"]["seaweed-mk02"].effect = { speed = {bonus = 2.0}, productivity = {bonus = 0.2}}
data.raw["module"]["seaweed-mk03"].effect = { speed = {bonus = 3.0}, productivity = {bonus = 0.3}}
data.raw["module"]["seaweed-mk04"].effect = { speed = {bonus = 4.0}, productivity = {bonus = 0.4}}
data.raw["module"]["ralesias-mk02"].effect = { speed = {bonus = 1.66}, productivity = {bonus = 0.2}}
data.raw["module"]["ralesias-mk03"].effect = { speed = {bonus = 2.49}, productivity = {bonus = 0.3}}
data.raw["module"]["ralesias-mk04"].effect = { speed = {bonus = 3.33}, productivity = {bonus = 0.4}}
data.raw["module"]["moss-mk02"].effect = { speed = {bonus = 1.3}, productivity = {bonus = 0.2}}
data.raw["module"]["moss-mk03"].effect = { speed = {bonus = 1.95}, productivity = {bonus = 0.3}}
data.raw["module"]["moss-mk04"].effect = { speed = {bonus = 2.6}, productivity = {bonus = 0.4}}
data.raw["module"]["grod-mk02"].effect = { speed = {bonus = 2.85}, productivity = {bonus = 0.2}}
data.raw["module"]["grod-mk03"].effect = { speed = {bonus = 4.27}, productivity = {bonus = 0.3}}
data.raw["module"]["grod-mk04"].effect = { speed = {bonus = 5.7}, productivity = {bonus = 0.4}}
data.raw["module"]["dhilmos-mk02"].effect = { speed = {bonus = 5.0}, productivity = {bonus = 0.2}}
data.raw["module"]["dhilmos-mk03"].effect = { speed = {bonus = 6.25}, productivity = {bonus = 0.3}}
data.raw["module"]["dhilmos-mk04"].effect = { speed = {bonus = 7.5}, productivity = {bonus = 0.4}}
data.raw["module"]["kicalk-mk02"].effect = { speed = {bonus = 0.5}, productivity = {bonus = 0.2}}
data.raw["module"]["kicalk-mk03"].effect = { speed = {bonus = 1.0}, productivity = {bonus = 0.3}}
data.raw["module"]["kicalk-mk04"].effect = { speed = {bonus = 1.5}, productivity = {bonus = 0.4}}
data.raw["module"]["bhoddos-mk02"].effect = { speed = {bonus = 50.0}, productivity = {bonus = 0.2}}
data.raw["module"]["bhoddos-mk03"].effect = { speed = {bonus = 55.0}, productivity = {bonus = 0.3}}
data.raw["module"]["bhoddos-mk04"].effect = { speed = {bonus = 60.0}, productivity = {bonus = 0.4}}
data.raw["module"]["tuuphra-mk02"].effect = { speed = {bonus = 2.0}, productivity = {bonus = 0.2}}
data.raw["module"]["tuuphra-mk03"].effect = { speed = {bonus = 3.0}, productivity = {bonus = 0.3}}
data.raw["module"]["tuuphra-mk04"].effect = { speed = {bonus = 4.0}, productivity = {bonus = 0.4}}
data.raw["module"]["auog-mk02"].effect = { speed = {bonus = 13.4}, productivity = {bonus = 0.2}}
data.raw["module"]["auog-mk03"].effect = { speed = {bonus = 20.1}, productivity = {bonus = 0.3}}
data.raw["module"]["auog-mk04"].effect = { speed = {bonus = 26.8}, productivity = {bonus = 0.4}}
data.raw["module"]["moondrop-mk02"].effect = { speed = {bonus = 1.0}, productivity = {bonus = 0.2}}
data.raw["module"]["moondrop-mk03"].effect = { speed = {bonus = 1.5}, productivity = {bonus = 0.3}}
data.raw["module"]["moondrop-mk04"].effect = { speed = {bonus = 2.0}, productivity = {bonus = 0.4}}
data.raw["module"]["sea-sponge-mk02"].effect = { speed = {bonus = 2.5}, productivity = {bonus = 0.2}}
data.raw["module"]["sea-sponge-mk03"].effect = { speed = {bonus = 4.0}, productivity = {bonus = 0.3}}
data.raw["module"]["sea-sponge-mk04"].effect = { speed = {bonus = 5.0}, productivity = {bonus = 0.4}}
data.raw["module"]["navens-mk02"].effect = { speed = {bonus = 10.0}, productivity = {bonus = 0.2}}
data.raw["module"]["navens-mk03"].effect = { speed = {bonus = 12.5}, productivity = {bonus = 0.3}}
data.raw["module"]["navens-mk04"].effect = { speed = {bonus = 15.0}, productivity = {bonus = 0.4}}
data.raw["module"]["korlex-mk02"].effect = { speed = {bonus = 3.13}, productivity = {bonus = 0.2}}
data.raw["module"]["korlex-mk03"].effect = { speed = {bonus = 3.75}, productivity = {bonus = 0.3}}
data.raw["module"]["korlex-mk04"].effect = { speed = {bonus = 4.38}, productivity = {bonus = 0.4}}
end
