data.raw["technology"]["space-science-pack"].prerequisites = 
    {
        "rocket-silo", 
        "electric-energy-accumulators", 
        "solar-energy", 
        "module-science-pack",
        "dark-module-science-pack",
        "Py-matter-VSD-science-pack",
        "Py-matter-YPR-science-pack",
        "Py-matter-KSR-science-pack",
        "Py-matter-MGD-science-pack",
        "Py-matter-KBT-science-pack",
        "Py-matter-AMS-science-pack",
        "Py-matter-NK-science-pack",
        "artillery-range-12",
        "build-distance-12",
        "crafting-speed-12",
        "health-bonus-12",
        "inventory-slots-bonus-12",
        "item-pickup-distance-12",
        "laboratory-productivity-12",
        "laboratory-speed-12",
        "loot-pickup-distance-12",
        "maximum-following-robots-count-12",
        "mining-drill-productivity-bonus-12",
        "reach-distance-12",
        "resource-reach-distance-12",
        "stack-inserter-capacity-bonus-12",
        "train-braking-force-bonus-12",
        "worker-robot-speed-12",
        "worker-robot-storage-12"
    }

--baseAddSC
    --space-science-pack
    data.raw["technology"]["space-science-pack"].unit.ingredients =
      {
        {"automation-science-pack", 1},
        {"logistic-science-pack", 1},
        {"chemical-science-pack", 1},
        {"production-science-pack", 1},
        {"utility-science-pack", 1},
        {"advanced-logistic-science-pack", 1},
        {"token-bio", 1},
        {"science-pack-gold", 1},
        {"alien-science-pack", 1},
        {"alien-science-pack-blue", 1},
        {"alien-science-pack-orange", 1},
        {"alien-science-pack-purple", 1},
        {"alien-science-pack-yellow", 1},
        {"alien-science-pack-green", 1},
        {"alien-science-pack-red", 1},
        {"speed-module-science-pack", 1},
        {"effectivity-module-science-pack", 1},
        {"productivity-module-science-pack", 1},
        {"pollution-clean-module-science-pack", 1},
        {"pollution-create-module-science-pack", 1},
        {"dark-module-science-pack", 1},
        {"Py-matter-vrauks-science-pack", 1},
        {"Py-matter-scrondrix-science-pack", 1},
        {"Py-matter-dingrits-science-pack", 1},
        {"Py-matter-yaedols-science-pack", 1},
        {"Py-matter-phagnot-science-pack", 1},
        {"Py-matter-rennea-science-pack", 1},
        {"Py-matter-kmauts-science-pack", 1},
        {"Py-matter-seaweed-science-pack", 1},
        {"Py-matter-ralesias-science-pack", 1},
        {"Py-matter-moss-science-pack", 1},
        {"Py-matter-grod-science-pack", 1},
        {"Py-matter-dhilmos-science-pack", 1},
        {"Py-matter-kicalk-science-pack", 1},
        {"Py-matter-bhoddos-science-pack", 1},
        {"Py-matter-tuuphra-science-pack", 1},
        {"Py-matter-auog-science-pack", 1},
        {"Py-matter-moondrop-science-pack", 1},
        {"Py-matter-sea-sponge-science-pack", 1},
        {"Py-matter-navens-science-pack", 1},
        {"Py-matter-korlex-science-pack", 1},
        {"module-case", 1},
        {"module-circuit-board", 1},
        {"speed-processor", 1},
        {"productivity-processor", 1},
        {"pollution-clean-processor", 1},
        {"pollution-create-processor", 1}          
      }
    --worker-robots-speed-6
    data.raw["technology"]["worker-robots-speed-6"].unit.ingredients =
      {
        {"automation-science-pack", 1},
        {"logistic-science-pack", 1},
        {"chemical-science-pack", 1},
        {"production-science-pack", 1},
        {"utility-science-pack", 1},
        {"space-science-pack", 1},
        {"speed-module-science-pack", 1},
        {"effectivity-module-science-pack", 1},
        {"productivity-module-science-pack", 1},
        {"pollution-clean-module-science-pack", 1},
        {"pollution-create-module-science-pack", 1},
        {"dark-module-science-pack", 1},
        {"Py-matter-vrauks-science-pack", 1},
        {"Py-matter-scrondrix-science-pack", 1},
        {"Py-matter-dingrits-science-pack", 1},
        {"Py-matter-yaedols-science-pack", 1},
        {"Py-matter-phagnot-science-pack", 1},
        {"Py-matter-rennea-science-pack", 1},
        {"Py-matter-kmauts-science-pack", 1},
        {"Py-matter-seaweed-science-pack", 1},
        {"Py-matter-ralesias-science-pack", 1},
        {"Py-matter-moss-science-pack", 1},
        {"Py-matter-grod-science-pack", 1},
        {"Py-matter-dhilmos-science-pack", 1},
        {"Py-matter-kicalk-science-pack", 1},
        {"Py-matter-bhoddos-science-pack", 1},
        {"Py-matter-tuuphra-science-pack", 1},
        {"Py-matter-auog-science-pack", 1},
        {"Py-matter-moondrop-science-pack", 1},
        {"Py-matter-sea-sponge-science-pack", 1},
        {"Py-matter-navens-science-pack", 1},
        {"Py-matter-korlex-science-pack", 1} 
      }
    --physical-projectile-damage-7
    data.raw["technology"]["physical-projectile-damage-7"].unit.ingredients =
      {
        {"automation-science-pack", 1},
        {"logistic-science-pack", 1},
        {"chemical-science-pack", 1},
        {"production-science-pack", 1},
        {"utility-science-pack", 1},
        {"space-science-pack", 1},
        {"speed-module-science-pack", 1},
        {"effectivity-module-science-pack", 1},
        {"productivity-module-science-pack", 1},
        {"pollution-clean-module-science-pack", 1},
        {"pollution-create-module-science-pack", 1},
        {"dark-module-science-pack", 1},
        {"Py-matter-vrauks-science-pack", 1},
        {"Py-matter-scrondrix-science-pack", 1},
        {"Py-matter-dingrits-science-pack", 1},
        {"Py-matter-yaedols-science-pack", 1},
        {"Py-matter-phagnot-science-pack", 1},
        {"Py-matter-rennea-science-pack", 1},
        {"Py-matter-kmauts-science-pack", 1},
        {"Py-matter-seaweed-science-pack", 1},
        {"Py-matter-ralesias-science-pack", 1},
        {"Py-matter-moss-science-pack", 1},
        {"Py-matter-grod-science-pack", 1},
        {"Py-matter-dhilmos-science-pack", 1},
        {"Py-matter-kicalk-science-pack", 1},
        {"Py-matter-bhoddos-science-pack", 1},
        {"Py-matter-tuuphra-science-pack", 1},
        {"Py-matter-auog-science-pack", 1},
        {"Py-matter-moondrop-science-pack", 1},
        {"Py-matter-sea-sponge-science-pack", 1},
        {"Py-matter-navens-science-pack", 1},
        {"Py-matter-korlex-science-pack", 1} 
      }
    --stronger-explosives-7
    data.raw["technology"]["stronger-explosives-7"].unit.ingredients =
      {
        {"automation-science-pack", 1},
        {"logistic-science-pack", 1},
        {"chemical-science-pack", 1},
        {"production-science-pack", 1},
        {"utility-science-pack", 1},
        {"space-science-pack", 1},
        {"speed-module-science-pack", 1},
        {"effectivity-module-science-pack", 1},
        {"productivity-module-science-pack", 1},
        {"pollution-clean-module-science-pack", 1},
        {"pollution-create-module-science-pack", 1},
        {"dark-module-science-pack", 1},
        {"Py-matter-vrauks-science-pack", 1},
        {"Py-matter-scrondrix-science-pack", 1},
        {"Py-matter-dingrits-science-pack", 1},
        {"Py-matter-yaedols-science-pack", 1},
        {"Py-matter-phagnot-science-pack", 1},
        {"Py-matter-rennea-science-pack", 1},
        {"Py-matter-kmauts-science-pack", 1},
        {"Py-matter-seaweed-science-pack", 1},
        {"Py-matter-ralesias-science-pack", 1},
        {"Py-matter-moss-science-pack", 1},
        {"Py-matter-grod-science-pack", 1},
        {"Py-matter-dhilmos-science-pack", 1},
        {"Py-matter-kicalk-science-pack", 1},
        {"Py-matter-bhoddos-science-pack", 1},
        {"Py-matter-tuuphra-science-pack", 1},
        {"Py-matter-auog-science-pack", 1},
        {"Py-matter-moondrop-science-pack", 1},
        {"Py-matter-sea-sponge-science-pack", 1},
        {"Py-matter-navens-science-pack", 1},
        {"Py-matter-korlex-science-pack", 1} 
      }
    --refined-flammables-7
    data.raw["technology"]["refined-flammables-7"].unit.ingredients =
      {
        {"automation-science-pack", 1},
        {"logistic-science-pack", 1},
        {"chemical-science-pack", 1},
        {"production-science-pack", 1},
        {"utility-science-pack", 1},
        {"space-science-pack", 1},
        {"speed-module-science-pack", 1},
        {"effectivity-module-science-pack", 1},
        {"productivity-module-science-pack", 1},
        {"pollution-clean-module-science-pack", 1},
        {"pollution-create-module-science-pack", 1},
        {"dark-module-science-pack", 1},
        {"Py-matter-vrauks-science-pack", 1},
        {"Py-matter-scrondrix-science-pack", 1},
        {"Py-matter-dingrits-science-pack", 1},
        {"Py-matter-yaedols-science-pack", 1},
        {"Py-matter-phagnot-science-pack", 1},
        {"Py-matter-rennea-science-pack", 1},
        {"Py-matter-kmauts-science-pack", 1},
        {"Py-matter-seaweed-science-pack", 1},
        {"Py-matter-ralesias-science-pack", 1},
        {"Py-matter-moss-science-pack", 1},
        {"Py-matter-grod-science-pack", 1},
        {"Py-matter-dhilmos-science-pack", 1},
        {"Py-matter-kicalk-science-pack", 1},
        {"Py-matter-bhoddos-science-pack", 1},
        {"Py-matter-tuuphra-science-pack", 1},
        {"Py-matter-auog-science-pack", 1},
        {"Py-matter-moondrop-science-pack", 1},
        {"Py-matter-sea-sponge-science-pack", 1},
        {"Py-matter-navens-science-pack", 1},
        {"Py-matter-korlex-science-pack", 1} 
      }
    --refined-flammables-7
    data.raw["technology"]["energy-weapons-damage-7"].unit.ingredients =
      {
        {"automation-science-pack", 1},
        {"logistic-science-pack", 1},
        {"chemical-science-pack", 1},
        {"production-science-pack", 1},
        {"utility-science-pack", 1},
        {"space-science-pack", 1},
        {"speed-module-science-pack", 1},
        {"effectivity-module-science-pack", 1},
        {"productivity-module-science-pack", 1},
        {"pollution-clean-module-science-pack", 1},
        {"pollution-create-module-science-pack", 1},
        {"dark-module-science-pack", 1},
        {"Py-matter-vrauks-science-pack", 1},
        {"Py-matter-scrondrix-science-pack", 1},
        {"Py-matter-dingrits-science-pack", 1},
        {"Py-matter-yaedols-science-pack", 1},
        {"Py-matter-phagnot-science-pack", 1},
        {"Py-matter-rennea-science-pack", 1},
        {"Py-matter-kmauts-science-pack", 1},
        {"Py-matter-seaweed-science-pack", 1},
        {"Py-matter-ralesias-science-pack", 1},
        {"Py-matter-moss-science-pack", 1},
        {"Py-matter-grod-science-pack", 1},
        {"Py-matter-dhilmos-science-pack", 1},
        {"Py-matter-kicalk-science-pack", 1},
        {"Py-matter-bhoddos-science-pack", 1},
        {"Py-matter-tuuphra-science-pack", 1},
        {"Py-matter-auog-science-pack", 1},
        {"Py-matter-moondrop-science-pack", 1},
        {"Py-matter-sea-sponge-science-pack", 1},
        {"Py-matter-navens-science-pack", 1},
        {"Py-matter-korlex-science-pack", 1} 
      }
    --artillery-shell-range-1
    data.raw["technology"]["artillery-shell-range-1"].unit.ingredients =
      {
        {"automation-science-pack", 1},
        {"logistic-science-pack", 1},
        {"chemical-science-pack", 1},
        {"production-science-pack", 1},
        {"utility-science-pack", 1},
        {"space-science-pack", 1},
        {"speed-module-science-pack", 1},
        {"effectivity-module-science-pack", 1},
        {"productivity-module-science-pack", 1},
        {"pollution-clean-module-science-pack", 1},
        {"pollution-create-module-science-pack", 1},
        {"dark-module-science-pack", 1},
        {"Py-matter-vrauks-science-pack", 1},
        {"Py-matter-scrondrix-science-pack", 1},
        {"Py-matter-dingrits-science-pack", 1},
        {"Py-matter-yaedols-science-pack", 1},
        {"Py-matter-phagnot-science-pack", 1},
        {"Py-matter-rennea-science-pack", 1},
        {"Py-matter-kmauts-science-pack", 1},
        {"Py-matter-seaweed-science-pack", 1},
        {"Py-matter-ralesias-science-pack", 1},
        {"Py-matter-moss-science-pack", 1},
        {"Py-matter-grod-science-pack", 1},
        {"Py-matter-dhilmos-science-pack", 1},
        {"Py-matter-kicalk-science-pack", 1},
        {"Py-matter-bhoddos-science-pack", 1},
        {"Py-matter-tuuphra-science-pack", 1},
        {"Py-matter-auog-science-pack", 1},
        {"Py-matter-moondrop-science-pack", 1},
        {"Py-matter-sea-sponge-science-pack", 1},
        {"Py-matter-navens-science-pack", 1},
        {"Py-matter-korlex-science-pack", 1} 
      }
    --artillery-shell-speed-1
    data.raw["technology"]["artillery-shell-speed-1"].unit.ingredients =
      {
        {"automation-science-pack", 1},
        {"logistic-science-pack", 1},
        {"chemical-science-pack", 1},
        {"production-science-pack", 1},
        {"utility-science-pack", 1},
        {"space-science-pack", 1},
        {"speed-module-science-pack", 1},
        {"effectivity-module-science-pack", 1},
        {"productivity-module-science-pack", 1},
        {"pollution-clean-module-science-pack", 1},
        {"pollution-create-module-science-pack", 1},
        {"dark-module-science-pack", 1},
        {"Py-matter-vrauks-science-pack", 1},
        {"Py-matter-scrondrix-science-pack", 1},
        {"Py-matter-dingrits-science-pack", 1},
        {"Py-matter-yaedols-science-pack", 1},
        {"Py-matter-phagnot-science-pack", 1},
        {"Py-matter-rennea-science-pack", 1},
        {"Py-matter-kmauts-science-pack", 1},
        {"Py-matter-seaweed-science-pack", 1},
        {"Py-matter-ralesias-science-pack", 1},
        {"Py-matter-moss-science-pack", 1},
        {"Py-matter-grod-science-pack", 1},
        {"Py-matter-dhilmos-science-pack", 1},
        {"Py-matter-kicalk-science-pack", 1},
        {"Py-matter-bhoddos-science-pack", 1},
        {"Py-matter-tuuphra-science-pack", 1},
        {"Py-matter-auog-science-pack", 1},
        {"Py-matter-moondrop-science-pack", 1},
        {"Py-matter-sea-sponge-science-pack", 1},
        {"Py-matter-navens-science-pack", 1},
        {"Py-matter-korlex-science-pack", 1} 
      }
    --follower-robot-count-7
    data.raw["technology"]["follower-robot-count-7"].unit.ingredients =
      {
        {"automation-science-pack", 1},
        {"logistic-science-pack", 1},
        {"chemical-science-pack", 1},
        {"production-science-pack", 1},
        {"utility-science-pack", 1},
        {"space-science-pack", 1},
        {"speed-module-science-pack", 1},
        {"effectivity-module-science-pack", 1},
        {"productivity-module-science-pack", 1},
        {"pollution-clean-module-science-pack", 1},
        {"pollution-create-module-science-pack", 1},
        {"dark-module-science-pack", 1},
        {"Py-matter-vrauks-science-pack", 1},
        {"Py-matter-scrondrix-science-pack", 1},
        {"Py-matter-dingrits-science-pack", 1},
        {"Py-matter-yaedols-science-pack", 1},
        {"Py-matter-phagnot-science-pack", 1},
        {"Py-matter-rennea-science-pack", 1},
        {"Py-matter-kmauts-science-pack", 1},
        {"Py-matter-seaweed-science-pack", 1},
        {"Py-matter-ralesias-science-pack", 1},
        {"Py-matter-moss-science-pack", 1},
        {"Py-matter-grod-science-pack", 1},
        {"Py-matter-dhilmos-science-pack", 1},
        {"Py-matter-kicalk-science-pack", 1},
        {"Py-matter-bhoddos-science-pack", 1},
        {"Py-matter-tuuphra-science-pack", 1},
        {"Py-matter-auog-science-pack", 1},
        {"Py-matter-moondrop-science-pack", 1},
        {"Py-matter-sea-sponge-science-pack", 1},
        {"Py-matter-navens-science-pack", 1},
        {"Py-matter-korlex-science-pack", 1} 
      }
    --mining-productivity-4
    data.raw["technology"]["mining-productivity-4"].unit.ingredients =
      {
        {"automation-science-pack", 1},
        {"logistic-science-pack", 1},
        {"chemical-science-pack", 1},
        {"production-science-pack", 1},
        {"utility-science-pack", 1},
        {"space-science-pack", 1},
        {"speed-module-science-pack", 1},
        {"effectivity-module-science-pack", 1},
        {"productivity-module-science-pack", 1},
        {"pollution-clean-module-science-pack", 1},
        {"pollution-create-module-science-pack", 1},
        {"dark-module-science-pack", 1},
        {"Py-matter-vrauks-science-pack", 1},
        {"Py-matter-scrondrix-science-pack", 1},
        {"Py-matter-dingrits-science-pack", 1},
        {"Py-matter-yaedols-science-pack", 1},
        {"Py-matter-phagnot-science-pack", 1},
        {"Py-matter-rennea-science-pack", 1},
        {"Py-matter-kmauts-science-pack", 1},
        {"Py-matter-seaweed-science-pack", 1},
        {"Py-matter-ralesias-science-pack", 1},
        {"Py-matter-moss-science-pack", 1},
        {"Py-matter-grod-science-pack", 1},
        {"Py-matter-dhilmos-science-pack", 1},
        {"Py-matter-kicalk-science-pack", 1},
        {"Py-matter-bhoddos-science-pack", 1},
        {"Py-matter-tuuphra-science-pack", 1},
        {"Py-matter-auog-science-pack", 1},
        {"Py-matter-moondrop-science-pack", 1},
        {"Py-matter-sea-sponge-science-pack", 1},
        {"Py-matter-navens-science-pack", 1},
        {"Py-matter-korlex-science-pack", 1} 
      }

--BobAddSC
if mods["boblogistics"] then
    --toolbelt-5
    data.raw["technology"]["toolbelt-5"].unit.ingredients =
      {
        {"automation-science-pack", 1},
        {"logistic-science-pack", 1},
        {"chemical-science-pack", 1},
        {"production-science-pack", 1},
        {"utility-science-pack", 1},
        {"space-science-pack", 1},
        {"speed-module-science-pack", 1},
        {"effectivity-module-science-pack", 1},
        {"productivity-module-science-pack", 1},
        {"pollution-clean-module-science-pack", 1},
        {"pollution-create-module-science-pack", 1},
        {"dark-module-science-pack", 1},
        {"Py-matter-vrauks-science-pack", 1},
        {"Py-matter-scrondrix-science-pack", 1},
        {"Py-matter-dingrits-science-pack", 1},
        {"Py-matter-yaedols-science-pack", 1},
        {"Py-matter-phagnot-science-pack", 1},
        {"Py-matter-rennea-science-pack", 1},
        {"Py-matter-kmauts-science-pack", 1},
        {"Py-matter-seaweed-science-pack", 1},
        {"Py-matter-ralesias-science-pack", 1},
        {"Py-matter-moss-science-pack", 1},
        {"Py-matter-grod-science-pack", 1},
        {"Py-matter-dhilmos-science-pack", 1},
        {"Py-matter-kicalk-science-pack", 1},
        {"Py-matter-bhoddos-science-pack", 1},
        {"Py-matter-tuuphra-science-pack", 1},
        {"Py-matter-auog-science-pack", 1},
        {"Py-matter-moondrop-science-pack", 1},
        {"Py-matter-sea-sponge-science-pack", 1},
        {"Py-matter-navens-science-pack", 1},
        {"Py-matter-korlex-science-pack", 1} 
      }
    --bob-infinite-character-logistic-trash-slots-1
    data.raw["technology"]["bob-infinite-character-logistic-trash-slots-1"].unit.ingredients =
      {
        {"automation-science-pack", 1},
        {"logistic-science-pack", 1},
        {"chemical-science-pack", 1},
        {"production-science-pack", 1},
        {"utility-science-pack", 1},
        {"space-science-pack", 1},
        {"speed-module-science-pack", 1},
        {"effectivity-module-science-pack", 1},
        {"productivity-module-science-pack", 1},
        {"pollution-clean-module-science-pack", 1},
        {"pollution-create-module-science-pack", 1},
        {"dark-module-science-pack", 1},
        {"Py-matter-vrauks-science-pack", 1},
        {"Py-matter-scrondrix-science-pack", 1},
        {"Py-matter-dingrits-science-pack", 1},
        {"Py-matter-yaedols-science-pack", 1},
        {"Py-matter-phagnot-science-pack", 1},
        {"Py-matter-rennea-science-pack", 1},
        {"Py-matter-kmauts-science-pack", 1},
        {"Py-matter-seaweed-science-pack", 1},
        {"Py-matter-ralesias-science-pack", 1},
        {"Py-matter-moss-science-pack", 1},
        {"Py-matter-grod-science-pack", 1},
        {"Py-matter-dhilmos-science-pack", 1},
        {"Py-matter-kicalk-science-pack", 1},
        {"Py-matter-bhoddos-science-pack", 1},
        {"Py-matter-tuuphra-science-pack", 1},
        {"Py-matter-auog-science-pack", 1},
        {"Py-matter-moondrop-science-pack", 1},
        {"Py-matter-sea-sponge-science-pack", 1},
        {"Py-matter-navens-science-pack", 1},
        {"Py-matter-korlex-science-pack", 1} 
      } 
    --bob-infinite-worker-robots-storage-4
    data.raw["technology"]["bob-infinite-worker-robots-storage-4"].unit.ingredients =
      {
        {"automation-science-pack", 1},
        {"logistic-science-pack", 1},
        {"chemical-science-pack", 1},
        {"production-science-pack", 1},
        {"utility-science-pack", 1},
        {"space-science-pack", 1},
        {"speed-module-science-pack", 1},
        {"effectivity-module-science-pack", 1},
        {"productivity-module-science-pack", 1},
        {"pollution-clean-module-science-pack", 1},
        {"pollution-create-module-science-pack", 1},
        {"dark-module-science-pack", 1},
        {"Py-matter-vrauks-science-pack", 1},
        {"Py-matter-scrondrix-science-pack", 1},
        {"Py-matter-dingrits-science-pack", 1},
        {"Py-matter-yaedols-science-pack", 1},
        {"Py-matter-phagnot-science-pack", 1},
        {"Py-matter-rennea-science-pack", 1},
        {"Py-matter-kmauts-science-pack", 1},
        {"Py-matter-seaweed-science-pack", 1},
        {"Py-matter-ralesias-science-pack", 1},
        {"Py-matter-moss-science-pack", 1},
        {"Py-matter-grod-science-pack", 1},
        {"Py-matter-dhilmos-science-pack", 1},
        {"Py-matter-kicalk-science-pack", 1},
        {"Py-matter-bhoddos-science-pack", 1},
        {"Py-matter-tuuphra-science-pack", 1},
        {"Py-matter-auog-science-pack", 1},
        {"Py-matter-moondrop-science-pack", 1},
        {"Py-matter-sea-sponge-science-pack", 1},
        {"Py-matter-navens-science-pack", 1},
        {"Py-matter-korlex-science-pack", 1} 
      }  
    --inserter-capacity-bonus-8
    data.raw["technology"]["inserter-capacity-bonus-8"].unit.ingredients =
      {
        {"automation-science-pack", 1},
        {"logistic-science-pack", 1},
        {"chemical-science-pack", 1},
        {"production-science-pack", 1},
        {"utility-science-pack", 1},
        {"space-science-pack", 1},
        {"speed-module-science-pack", 1},
        {"effectivity-module-science-pack", 1},
        {"productivity-module-science-pack", 1},
        {"pollution-clean-module-science-pack", 1},
        {"pollution-create-module-science-pack", 1},
        {"dark-module-science-pack", 1},
        {"Py-matter-vrauks-science-pack", 1},
        {"Py-matter-scrondrix-science-pack", 1},
        {"Py-matter-dingrits-science-pack", 1},
        {"Py-matter-yaedols-science-pack", 1},
        {"Py-matter-phagnot-science-pack", 1},
        {"Py-matter-rennea-science-pack", 1},
        {"Py-matter-kmauts-science-pack", 1},
        {"Py-matter-seaweed-science-pack", 1},
        {"Py-matter-ralesias-science-pack", 1},
        {"Py-matter-moss-science-pack", 1},
        {"Py-matter-grod-science-pack", 1},
        {"Py-matter-dhilmos-science-pack", 1},
        {"Py-matter-kicalk-science-pack", 1},
        {"Py-matter-bhoddos-science-pack", 1},
        {"Py-matter-tuuphra-science-pack", 1},
        {"Py-matter-auog-science-pack", 1},
        {"Py-matter-moondrop-science-pack", 1},
        {"Py-matter-sea-sponge-science-pack", 1},
        {"Py-matter-navens-science-pack", 1},
        {"Py-matter-korlex-science-pack", 1} 
      } 
end

--tool
data:extend({
  --module
      {
        type = "tool",
        name = "speed-module-science-pack",
        icon = "__MyModPackMuit__/graphics/icons/M1-Sp.png",
        icon_size = 64,
        subgroup = "science-pack",
        order = "e[speed-module-science-pack]",
        stack_size = 10000,
        durability = 1,
        durability_description_key = "description.science-pack-remaining-amount-key",
        durability_description_value = "description.science-pack-remaining-amount-value"
      },
      {
        type = "tool",
        name = "effectivity-module-science-pack",
        icon = "__MyModPackMuit__/graphics/icons/M2-Sp.png",
        icon_size = 64,
        subgroup = "science-pack",
        order = "e[effectivity-module-science-pack]",
        stack_size = 10000,
        durability = 1,
        durability_description_key = "description.science-pack-remaining-amount-key",
        durability_description_value = "description.science-pack-remaining-amount-value"
      },
      {
        type = "tool",
        name = "productivity-module-science-pack",
        icon = "__MyModPackMuit__/graphics/icons/M3-Sp.png",
        icon_size = 64,
        subgroup = "science-pack",
        order = "e[productivity-module-science-pack]",
        stack_size = 10000,
        durability = 1,
        durability_description_key = "description.science-pack-remaining-amount-key",
        durability_description_value = "description.science-pack-remaining-amount-value"
      },
      {
        type = "tool",
        name = "pollution-clean-module-science-pack",
        icon = "__MyModPackMuit__/graphics/icons/M4-Sp.png",
        icon_size = 64,
        subgroup = "science-pack",
        order = "e[pollution-clean-module-science-pack]",
        stack_size = 10000,
        durability = 1,
        durability_description_key = "description.science-pack-remaining-amount-key",
        durability_description_value = "description.science-pack-remaining-amount-value"
      },
      {
        type = "tool",
        name = "pollution-create-module-science-pack",
        icon = "__MyModPackMuit__/graphics/icons/M5-Sp.png",
        icon_size = 64,
        subgroup = "science-pack",
        order = "e[pollution-create-module-science-pack]",
        stack_size = 10000,
        durability = 1,
        durability_description_key = "description.science-pack-remaining-amount-key",
        durability_description_value = "description.science-pack-remaining-amount-value"
      },
  --dark
      {
        type = "tool",
        name = "dark-module-science-pack",
        icon = "__MyModPackMuit__/graphics/icons/M6-Sp.png",
        icon_size = 64,
        subgroup = "science-pack",
        order = "e[dark-module-science-pack]",
        stack_size = 10000,
        durability = 1,
        durability_description_key = "description.science-pack-remaining-amount-key",
        durability_description_value = "description.science-pack-remaining-amount-value"
      }
}
)

--recipe
data:extend({
  --module
      {
        type = "recipe",
        name = "speed-module-science-pack",
        enabled = false,
        energy_required = 100,
        ingredients = {
          {"speed-module", 10},
          {"speed-module-2", 10},
          {"speed-module-3", 10},
          {"speed-module-4", 10},
          {"speed-module-5", 10},
          {"speed-module-6", 10},
          {"speed-module-7", 10},
          {"speed-module-8", 10},
        },
        result_count = 1,
        result = "speed-module-science-pack"
      },
      {
        type = "recipe",
        name = "effectivity-module-science-pack",
        enabled = false,
        energy_required = 100,
        ingredients = {
          {"effectivity-module", 10},
          {"effectivity-module-2", 10},
          {"effectivity-module-3", 10},
          {"effectivity-module-4", 10},
          {"effectivity-module-5", 10},
          {"effectivity-module-6", 10},
          {"effectivity-module-7", 10},
          {"effectivity-module-8", 10},
        },
        result_count = 1,
        result = "effectivity-module-science-pack"
      },
      {
        type = "recipe",
        name = "productivity-module-science-pack",
        enabled = false,
        energy_required = 100,
        ingredients = {
          {"productivity-module", 10},
          {"productivity-module-2", 10},
          {"productivity-module-3", 10},
          {"productivity-module-4", 10},
          {"productivity-module-5", 10},
          {"productivity-module-6", 10},
          {"productivity-module-7", 10},
          {"productivity-module-8", 10},
        },
        result_count = 1,
        result = "productivity-module-science-pack"
      },
      {
        type = "recipe",
        name = "pollution-clean-module-science-pack",
        enabled = false,
        energy_required = 100,
        ingredients = {
          {"pollution-clean-module-1", 10},
          {"pollution-clean-module-2", 10},
          {"pollution-clean-module-3", 10},
          {"pollution-clean-module-4", 10},
          {"pollution-clean-module-5", 10},
          {"pollution-clean-module-6", 10},
          {"pollution-clean-module-7", 10},
          {"pollution-clean-module-8", 10},
        },
        result_count = 1,
        result = "pollution-clean-module-science-pack"
      },
      {
        type = "recipe",
        name = "pollution-create-module-science-pack",
        enabled = false,
        energy_required = 100,
        ingredients = {
          {"pollution-create-module-1", 10},
          {"pollution-create-module-2", 10},
          {"pollution-create-module-3", 10},
          {"pollution-create-module-4", 10},
          {"pollution-create-module-5", 10},
          {"pollution-create-module-6", 10},
          {"pollution-create-module-7", 10},
          {"pollution-create-module-8", 10},
        },
        result_count = 1,
        result = "pollution-create-module-science-pack"
      },
  --dark
      {
        type = "recipe",
        name = "dark-module-science-pack",
        enabled = false,
        energy_required = 100,
        ingredients = {
          {"dark-module-1", 10},
          {"dark-module-2", 10},
          {"dark-module-3", 10},
        },
        result_count = 1,
        result = "dark-module-science-pack"
      },
}
)

--technology
data:extend({
  --module
      {
        type = "technology",
        name = "module-science-pack",
        icon = "__MyModPackMuit__/graphics/technology/M1-Sp.png",
        icon_size = 256,
        order = "c-k-m-a",
        prerequisites = {
          "speed-module-8", "effectivity-module-8", "productivity-module-8", "pollution-clean-module-8", "pollution-create-module-8"
        },
        effects = {
          {
            type = "unlock-recipe",
            recipe = "speed-module-science-pack"
          },
          {
            type = "unlock-recipe",
            recipe = "effectivity-module-science-pack"
          },
          {
            type = "unlock-recipe",
            recipe = "productivity-module-science-pack"
          },
          {
            type = "unlock-recipe",
            recipe = "pollution-clean-module-science-pack"
          },
          {
            type = "unlock-recipe",
            recipe = "pollution-create-module-science-pack"
          },
        },
        unit = {
          count = 100,
          time = 30,
          ingredients = {
            {"automation-science-pack", 1},
            {"logistic-science-pack", 1},
            {"chemical-science-pack", 1}
          },
        },
      },
  --dark
      {
        type = "technology",
        name = "dark-module-science-pack",
        icon = "__MyModPackMuit__/graphics/technology/M2-Sp.png",
        icon_size = 256,
        order = "c-k-m-a",
        prerequisites = {
          "dark-module-3"
        },
        effects = {
          {
            type = "unlock-recipe",
            recipe = "dark-module-science-pack"
          },
        },
        unit = {
          count = 100,
          time = 30,
          ingredients = {
            {"automation-science-pack", 1},
            {"logistic-science-pack", 1},
            {"chemical-science-pack", 1}
          },
        },
      },
}
)